application: namethatoliner
version: 1
runtime: python
api_version: 1

handlers:
- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin
    
- url: /images
  static_dir: images
  
- url: /css
  static_dir: css
  
- url: /js
  static_dir: js
  
- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
  
- url: /loadperson
  script: loader_person.py

- url: /.*
  script: main.py